version: '3.8'

services:
  app:
    image: yiisoftware/yii2-php:8.4-fpm
    container_name: yii2-app
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis
      - rabbitmq
    environment:
      YII_ENV: dev
      MYSQL_HOST: yii2-mysql
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASSWORD}
    networks:
      - yii2-net


  nginx:
    image: nginx:alpine
    container_name: yii2-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - yii2-net

  mysql:
    image: mysql:8.0
    container_name: yii2-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - yii2-net

  redis:
    image: redis:7-alpine
    container_name: yii2-redis
    ports:
      - "6379:6379"
    networks:
      - yii2-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: yii2-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - yii2-net

volumes:
  mysql-data:

networks:
  yii2-net:
    driver: bridge
